export const FETCH_BY_POKEMONS_REQEST = 'FETCH_BY_POKEMONS_REQEST';
export const FETCH_BY_POKEMONS_SUCCESS = 'FETCH_BY_POKEMONS_SUCCESS';
export const FETCH_BY_POKEMONS_ERROR = 'FETCH_BY_POKEMONS_ERROR';
