export const FETCH_POKEMONS_REQEST = 'FETCH_POKEMONS_REQEST';
export const FETCH_POKEMONS_SUCCESS = 'FETCH_POKEMONS_SUCCESS';
export const FETCH_POKEMONS_ERROR = 'FETCH_POKEMONS_ERROR';
export const FETCH_POKEMON_DETAIL_REQEST = 'FETCH_POKEMON_DETAIL_REQEST';
export const FETCH_POKEMON_DETAIL_SUCCESS = 'FETCH_POKEMON_DETAIL_SUCCESS';
export const FETCH_POKEMON_DETAIL_ERROR = 'FETCH_POKEMON_DETAIL_ERROR';
